try: 
    x="Name Error Exception" 
    print(y)
except NameError: 
    print("Name Error Exception is Caught")

